# Repository settings
# This file is automatically applied by the .github/workflows/sync-repo-settings.yml workflow
# Edit this file and push to main branch to update repository settings
# See: .github/README.md for documentation

repository:
  # General settings
  name: volumized-dev
  description: "A fully isolated, reproducible development environment using VS Code, Docker, and OrbStack"
  homepage: https://github.com/jfheinrich-eu/volumized-dev
  topics:
    - docker
    - devcontainer
    - vscode
    - development-environment
    - apple-silicon
    - orbstack
    - isolated-environment
    - volume-based

  # Repository features
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  has_discussions: false

  # Security settings
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

  # Default branch
  default_branch: main

# Branch protection rules
branches:
  - name: main
    protection:
      # Require pull request reviews before merging
      required_pull_request_reviews:
        # Dismiss stale reviews when new commits are pushed
        dismiss_stale_reviews: true
        # Require review from Code Owners
        require_code_owner_reviews: true
        # Number of approvals required
        required_approving_review_count: 1
        # Restrict who can dismiss pull request reviews
        dismissal_restrictions:
          users: []
          teams:
            - maintainers

      # Require status checks to pass before merging
      required_status_checks:
        # Require branches to be up to date before merging
        strict: true
        # Status checks that must pass
        contexts: []

      # Enforce restrictions on pushing to the branch
      enforce_admins: false

      # Require signed commits
      required_signatures: false

      # Restrict who can push to matching branches
      restrictions:
        users: []
        teams:
          - maintainers
        apps:
          - jfheinrich-bot

      # Require linear history
      required_linear_history: false

      # Allow force pushes
      allow_force_pushes: false

      # Allow deletions
      allow_deletions: false

      # Require conversation resolution before merging
      required_conversation_resolution: true

      # Lock branch (read-only)
      lock_branch: false

      # Allow fork syncing
      allow_fork_syncing: true

# Collaborators and teams
# Note: This requires organization membership and proper team setup
teams:
  - name: maintainers
    permission: admin

# Labels for issues and PRs
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working

  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation

  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists

  - name: enhancement
    color: a2eeef
    description: New feature or request

  - name: good first issue
    color: 7057ff
    description: Good for newcomers

  - name: help wanted
    color: 008672
    description: Extra attention is needed

  - name: invalid
    color: e4e669
    description: This doesn't seem right

  - name: question
    color: d876e3
    description: Further information is requested

  - name: wontfix
    color: ffffff
    description: This will not be worked on

  - name: security
    color: ee0701
    description: Security-related issue or fix

  - name: dependencies
    color: 0366d6
    description: Pull requests that update a dependency file

  - name: automated
    color: 1d76db
    description: Automated action or bot-created issue/PR

# Milestones (optional)
milestones: []

# Rulesets (GitHub's newer alternative to branch protection)
# Note: Requires GitHub Enterprise or specific plans
# Uncomment and configure if available in your plan
# rulesets:
#   - name: main-branch-protection
#     target: branch
#     enforcement: active
#     conditions:
#       ref_name:
#         include:
#           - "~DEFAULT_BRANCH"
#     rules:
#       - type: pull_request
#         parameters:
#           required_approving_review_count: 1
#           dismiss_stale_reviews_on_push: true
#           require_code_owner_review: true
#           require_last_push_approval: false
#       - type: required_status_checks
#         parameters:
#           strict_required_status_checks_policy: true
#           required_status_checks: []
#       - type: required_signatures
#       - type: deletion
